xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    QObs(mm/d):
      dims: []
      attrs: {}
      data: 2.2269930839538574
    prcp(mm/day):
      dims: []
      attrs: {}
      data: 8.65960693359375
    srad(W/m2):
      dims: []
      attrs: {}
      data: 116.7378158569336
    tmax(C):
      dims: []
      attrs: {}
      data: 9.886303901672363
    tmin(C):
      dims: []
      attrs: {}
      data: 9.3480806350708
    vp(Pa):
      dims: []
      attrs: {}
      data: 596.3735961914062
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    QObs(mm/d):
      dims: []
      attrs: {}
      data: 1.6205909252166748
    prcp(mm/day):
      dims: []
      attrs: {}
      data: 3.7900493144989014
    srad(W/m2):
      dims: []
      attrs: {}
      data: 311.7364807128906
    tmax(C):
      dims: []
      attrs: {}
      data: 15.174241065979004
    tmin(C):
      dims: []
      attrs: {}
      data: 4.366180419921875
    vp(Pa):
      dims: []
      attrs: {}
      data: 992.4519653320312
